blank_issues_enabled: false
contact_links:
  - name: "Contact Notion (Vendor Support)"
    url: https://www.notion.com/help
    about: "To get help from the Vendor, please use this link or write to: team@makenotion.com"
