enum notion_database_property_format_type
# https://developers.notion.com/reference/property-object#number
{
    argentine_peso
    baht
    australian_dollar
    canadian_dollar
    chilean_peso
    colombian_peso
    danish_krone
    dirham
    dollar
    euro
    forint
    franc
    hong_kong_dollar
    koruna
    krona
    leu
    lira
    mexican_peso
    new_taiwan_dollar
    new_zealand_dollar
    norwegian_krone
    number
    number_with_commas
    percent
    philippine_peso
    pound
    peruvian_sol
    rand
    real
    ringgit
    riyal
    ruble
    rupee
    rupiah
    shekel
    singapore_dollar
    uruguayan_peso
    yen
    yuan
    won
    zloty
}
