name: Tag on Merge & Publish

on:
  push:
    branches:
      - main
      - dev

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push tags
    outputs:
      tag: ${{ steps.gitversion.outputs.SemVer }}  # Store the generated version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for GitVersion

      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine version
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0

      - name: Create and push tag
        run: |
          git tag v${{ steps.gitversion.outputs.SemVer }}
          git push origin v${{ steps.gitversion.outputs.SemVer }}

  build-and-publish:
    runs-on: ubuntu-latest
    needs: versioning  # Waits for versioning job to finish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for GitVersion

      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Package Module
        run: |
          ./build.ps1 -ResolveDependency -UseModuleFast -Task pack

      - name: Publish Module
        env:
          GalleryApiToken: ${{ secrets.PSGALLERY_API_KEY }}
          GitHubToken: ${{ secrets.GH_TOKEN }}
        run: |
          ./build.ps1 -ResolveDependency -UseModuleFast -Task publish
