name: Tag and Publish PowerShell Module
on:
  push:
    branches:
      - main
      - dev

defaults:
  run:
    shell: powershell

jobs:
  tag-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all commits and tags are fetched

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.1

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Create and Push Tag
        run: |
          TAG="v${{ steps.gitversion.outputs.SemVer }}"
          git tag "$TAG"
          git push origin "$TAG"

      - name: Set execute permissions for build.ps1
        run: chmod +x ./build.ps1

      - name: Package Module
        run: |
          ./build.ps1 -ResolveDependency -UseModuleFast -Task pack

      - name: Publish Module
        env:
          GalleryApiToken: ${{ secrets.PSGALLERY_API_KEY }}
          GitHubToken: ${{ secrets.GH_TOKEN }}
        run: |
          ./build.ps1 -ResolveDependency -UseModuleFast -Task publish
